package piscine

import "fmt"

func Ascii_art_maj(letter string) {
	if letter == "a" {
		fmt.Println("    /\\")
		fmt.Println("   /  \\")
		fmt.Println("  / /\\ \\")
		fmt.Println(" / ____ \\")
		fmt.Println("/_/    \\_\\ ")
	} else if letter == "b" {
		fmt.Println(" ____ ")
		fmt.Println("|  _ \\")
		fmt.Println("| |_) | ")
		fmt.Println("|  _ < ")
		fmt.Println("| |_) |")
		fmt.Println("|____/")
	} else if letter == "c" {
		fmt.Println("  _____  ")
		fmt.Println(" / ____| ")
		fmt.Println("| |      ")
		fmt.Println("| |      ")
		fmt.Println("| |____  ")
		fmt.Println(" \\_____| ")
	} else if letter == "d" {
		fmt.Println(" _____   ")
		fmt.Println("|  __ \\ ")
		fmt.Println("| |  | | ")
		fmt.Println("| |  | | ")
		fmt.Println("| |__| | ")
		fmt.Println("|_____/  ")
	} else if letter == "e" {
		fmt.Println(" ______  ")
		fmt.Println("|  ____| ")
		fmt.Println("| |__    ")
		fmt.Println("|  __|   ")
		fmt.Println("| |____  ")
		fmt.Println("|______| ")
	} else if letter == "f" {
		fmt.Println(" ______  ")
		fmt.Println("|  ____| ")
		fmt.Println("| |__    ")
		fmt.Println("|  __|   ")
		fmt.Println("| |      ")
		fmt.Println("|_|      ")
	} else if letter == "g" {
		fmt.Println("  _____  ")
		fmt.Println(" / ____| ")
		fmt.Println("| |  __  ")
		fmt.Println("| | |_ | ")
		fmt.Println("| |__| | ")
		fmt.Println(" \\_____| ")
	} else if letter == "h" {
		fmt.Println(" _    _  ")
		fmt.Println("| |  | | ")
		fmt.Println("| |__| | ")
		fmt.Println("|  __  | ")
		fmt.Println("| |  | | ")
		fmt.Println("|_|  |_| ")
	} else if letter == "i" {
		fmt.Println(" _____  ")
		fmt.Println("|_   _| ")
		fmt.Println("  | |   ")
		fmt.Println("  | |   ")
		fmt.Println(" _| |_  ")
		fmt.Println("|_____| ")
	} else if letter == "j" {
		fmt.Println("      _  ")
		fmt.Println("     | | ")
		fmt.Println("     | | ")
		fmt.Println(" _   | | ")
		fmt.Println("| |__| | ")
		fmt.Println(" \\____/  ")
	} else if letter == "k" {
		fmt.Println(" _  __ ")
		fmt.Println("| |/ / ")
		fmt.Println("| ' /  ")
		fmt.Println("|  <   ")
		fmt.Println("| . \\  ")
		fmt.Println("|_|\\_\\ ")
	} else if letter == "l" {
		fmt.Println(" _       ")
		fmt.Println("| |      ")
		fmt.Println("| |      ")
		fmt.Println("| |      ")
		fmt.Println("| |____  ")
		fmt.Println("|______| ")
	} else if letter == "m" {
		fmt.Println(" __  __  ")
		fmt.Println("|  \\/  | ")
		fmt.Println("| \\  / | ")
		fmt.Println("| |\\/| | ")
		fmt.Println("| |  | | ")
		fmt.Println("|_|  |_| ")
	} else if letter == "n" {
		fmt.Println(" _   _  ")
		fmt.Println("| \\ | | ")
		fmt.Println("|  \\| | ")
		fmt.Println("| . ` | ")
		fmt.Println("| |\\  | ")
		fmt.Println("|_| \\_| ")
	} else if letter == "o" {
		fmt.Println("  ____   ")
		fmt.Println(" / __ \\  ")
		fmt.Println("| |  | | ")
		fmt.Println("| |  | | ")
		fmt.Println("| |__| | ")
		fmt.Println(" \\____/  ")
	} else if letter == "p" {
		fmt.Println(" _____   ")
		fmt.Println("|  __ \\  ")
		fmt.Println("| |__) | ")
		fmt.Println("|  ___/  ")
		fmt.Println("| |      ")
		fmt.Println("|_|      ")
	} else if letter == "q" {
		fmt.Println("  ____   ")
		fmt.Println(" / __ \\  ")
		fmt.Println("| |  | | ")
		fmt.Println("| |  | | ")
		fmt.Println("| |__| | ")
		fmt.Println(" \\___\\_\\ ")
	} else if letter == "r" {
		fmt.Println(" _____   ")
		fmt.Println("|  __ \\  ")
		fmt.Println("| |__) | ")
		fmt.Println("|  _  /  ")
		fmt.Println("| | \\ \\  ")
		fmt.Println("|_|  \\_\\ ")
	} else if letter == "s" {
		fmt.Println("  _____  ")
		fmt.Println(" / ____| ")
		fmt.Println("| (___   ")
		fmt.Println(" \\___ \\  ")
		fmt.Println(" ____) | ")
		fmt.Println("|_____/  ")
	} else if letter == "t" {
		fmt.Println(" _______  ")
		fmt.Println("|__   __| ")
		fmt.Println("   | |    ")
		fmt.Println("   | |    ")
		fmt.Println("   | |    ")
		fmt.Println("   |_|    ")
	} else if letter == "u" {
		fmt.Println(" _    _  ")
		fmt.Println("| |  | | ")
		fmt.Println("| |  | | ")
		fmt.Println("| |  | | ")
		fmt.Println("| |__| | ")
		fmt.Println(" \\____/  ")
	} else if letter == "v" {
		fmt.Println("__      __ ")
		fmt.Println("\\ \\    / / ")
		fmt.Println(" \\ \\  / /  ")
		fmt.Println("  \\ \\/ /   ")
		fmt.Println("   \\  /    ")
		fmt.Println("    \\/     ")
	} else if letter == "w" {
		fmt.Println("__          __ ")
		fmt.Println("\\ \\        / / ")
		fmt.Println(" \\ \\  /\\  / /  ")
		fmt.Println("  \\ \\/  \\/ /   ")
		fmt.Println("   \\  /\\  /    ")
		fmt.Println("    \\/  \\/     ")
	} else if letter == "x" {
		fmt.Println("__   __ ")
		fmt.Println("\\ \\ / / ")
		fmt.Println(" \\ V /  ")
		fmt.Println("  > <   ")
		fmt.Println(" / . \\  ")
		fmt.Println("/_/ \\_\\ ")
	} else if letter == "y" {
		fmt.Println("__     __ ")
		fmt.Println("\\ \\   / / ")
		fmt.Println(" \\ \\_/ /  ")
		fmt.Println("  \\   /   ")
		fmt.Println("   | |    ")
		fmt.Println("   |_|    ")
	} else if letter == "z" {
		fmt.Println(" ______ ")
		fmt.Println("|___  / ")
		fmt.Println("   / /  ")
		fmt.Println("  / /   ")
		fmt.Println(" / /__  ")
		fmt.Println("/_____| ")
	}
}
func underscore() {
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println(" ______ ")
	fmt.Println("|______|")
}

func Point() {
	fmt.Println(" _  ")
	fmt.Println("(_) ")
}
